using System;
using System.Collections.ObjectModel;
using Avalonia.Collections;

namespace Romzetron.Avalonia.Example.ViewModels;

public class DataGridViewModel : ViewModelBase
{
    //==================================================
    // Properties.
    //==================================================

    public ObservableCollection<ProductViewModel> Products { get; } =
    [
        new()
        {
            ProductID = 1,
            Name = "Week",
            Category = "Furniture",
            Manufacturer = "Poole, Stone and Santana",
            Price = 19.09,
            StockQuantity = 32,
            DateAdded = DateTime.Parse("2023-06-24"),
            LastRestocked = DateTime.Parse("2024-07-10"),
            IsAvailable = true,
            SKU = "e14ce913-b107-4e62-b791-7044722143b2",
            WarehouseLocation = "C3",
            Weight = 40.12,
            Dimensions = 187.25,
            Color = "Red",
            Material = "Glass",
            Warranty = "3 Years",
            Supplier = "Copeland and Sons",
            Description = "Their not why opportunity.",
            Discount = 22.67,
            CustomerRating = 5,
            TimesPurchased = 738
        },
        new()
        {
            ProductID = 2,
            Name = "Reach",
            Category = "Clothing",
            Manufacturer = "Camacho PLC",
            Price = 53.28,
            StockQuantity = 100,
            DateAdded = DateTime.Parse("2022-01-26"),
            LastRestocked = DateTime.Parse("2024-05-23"),
            IsAvailable = true,
            SKU = "84a06a40-e248-4010-a65f-6e0ab0fc119e",
            WarehouseLocation = "A1",
            Weight = 8.66,
            Dimensions = 85.32,
            Color = "Yellow",
            Material = "Wood",
            Warranty = "No Warranty",
            Supplier = "Sanford-Beard",
            Description = "Theory theory yeah certain must.",
            Discount = 9.24,
            CustomerRating = 3,
            TimesPurchased = 299
        },
        new()
        {
            ProductID = 3,
            Name = "Manager",
            Category = "Toys",
            Manufacturer = "Dixon and Sons",
            Price = 426.48,
            StockQuantity = 63,
            DateAdded = DateTime.Parse("2022-12-05"),
            LastRestocked = DateTime.Parse("2024-09-10"),
            IsAvailable = true,
            SKU = "c9e3d6c4-ed50-4bc7-84fa-00ce3237ba35",
            WarehouseLocation = "A1",
            Weight = 47.07,
            Dimensions = 193.0,
            Color = "Yellow",
            Material = "Plastic",
            Warranty = "1 Year",
            Supplier = "West-Green",
            Description = "Some food real community husband exactly.",
            Discount = 7.85,
            CustomerRating = 2,
            TimesPurchased = 897
        },
        new()
        {
            ProductID = 4,
            Name = "Same",
            Category = "Clothing",
            Manufacturer = "Page and Sons",
            Price = 348.09,
            StockQuantity = 4,
            DateAdded = DateTime.Parse("2021-07-28"),
            LastRestocked = DateTime.Parse("2024-03-14"),
            IsAvailable = false,
            SKU = "19f1f318-d17a-4145-96e0-f8bd1a3053ef",
            WarehouseLocation = "B2",
            Weight = 47.26,
            Dimensions = 129.34,
            Color = "Black",
            Material = "Metal",
            Warranty = "2 Years",
            Supplier = "Powell, Kelly and Obrien",
            Description = "Difference rule begin small.",
            Discount = 25.13,
            CustomerRating = 2,
            TimesPurchased = 723
        },
        new()
        {
            ProductID = 5,
            Name = "Participant",
            Category = "Clothing",
            Manufacturer = "Lozano, Alvarez and Johnson",
            Price = 11.18,
            StockQuantity = 73,
            DateAdded = DateTime.Parse("2022-03-11"),
            LastRestocked = DateTime.Parse("2024-07-14"),
            IsAvailable = true,
            SKU = "dc84cf2b-7d4f-4c40-864a-a0a13bf7f411",
            WarehouseLocation = "E5",
            Weight = 22.09,
            Dimensions = 50.85,
            Color = "Yellow",
            Material = "Metal",
            Warranty = "3 Years",
            Supplier = "Potter Inc",
            Description = "Inside though early would can sometimes lay.",
            Discount = 16.04,
            CustomerRating = 2,
            TimesPurchased = 317
        },
        new()
        {
            ProductID = 6,
            Name = "Him",
            Category = "Electronics",
            Manufacturer = "Barnes Inc",
            Price = 485.08,
            StockQuantity = 2,
            DateAdded = DateTime.Parse("2024-04-19"),
            LastRestocked = DateTime.Parse("2024-10-03"),
            IsAvailable = true,
            SKU = "456d4d54-5dec-421b-bf4a-d801414b8be6",
            WarehouseLocation = "C3",
            Weight = 17.28,
            Dimensions = 73.72,
            Color = "Blue",
            Material = "Plastic",
            Warranty = "No Warranty",
            Supplier = "King, Weber and Davis",
            Description = "Different group fight expert show.",
            Discount = 22.48,
            CustomerRating = 5,
            TimesPurchased = 825
        },
        new()
        {
            ProductID = 7,
            Name = "Technology",
            Category = "Electronics",
            Manufacturer = "Patel and Sons",
            Price = 117.67,
            StockQuantity = 30,
            DateAdded = DateTime.Parse("2021-08-06"),
            LastRestocked = DateTime.Parse("2024-04-08"),
            IsAvailable = true,
            SKU = "f0644ddb-8f12-4a7a-bf11-344c53425a68",
            WarehouseLocation = "B2",
            Weight = 21.29,
            Dimensions = 99.01,
            Color = "White",
            Material = "Metal",
            Warranty = "No Warranty",
            Supplier = "Taylor-Blake",
            Description = "Whole nation member trade majority part current.",
            Discount = 25.37,
            CustomerRating = 3,
            TimesPurchased = 261
        },
        new()
        {
            ProductID = 8,
            Name = "Blue",
            Category = "Clothing",
            Manufacturer = "Carter Ltd",
            Price = 329.36,
            StockQuantity = 68,
            DateAdded = DateTime.Parse("2021-06-14"),
            LastRestocked = DateTime.Parse("2024-04-13"),
            IsAvailable = true,
            SKU = "49195def-a1b9-4d98-9b6f-95c66701bffe",
            WarehouseLocation = "C3",
            Weight = 35.48,
            Dimensions = 117.35,
            Color = "Red",
            Material = "Glass",
            Warranty = "1 Year",
            Supplier = "Abbott-Warner",
            Description = "Drop long here major laugh either.",
            Discount = 27.47,
            CustomerRating = 1,
            TimesPurchased = 410
        },
        new()
        {
            ProductID = 9,
            Name = "Before",
            Category = "Furniture",
            Manufacturer = "Allen-Brennan",
            Price = 364.26,
            StockQuantity = 28,
            DateAdded = DateTime.Parse("2024-11-02"),
            LastRestocked = DateTime.Parse("2024-06-23"),
            IsAvailable = true,
            SKU = "d5a5cbce-102e-4e50-bef0-59c353e3dca3",
            WarehouseLocation = "B2",
            Weight = 30.16,
            Dimensions = 146.36,
            Color = "Green",
            Material = "Metal",
            Warranty = "2 Years",
            Supplier = "Ryan Inc",
            Description = "Accept probably show make.",
            Discount = 25.43,
            CustomerRating = 1,
            TimesPurchased = 844
        },
        new()
        {
            ProductID = 10,
            Name = "Reality",
            Category = "Toys",
            Manufacturer = "Oliver, Alexander and Hamilton",
            Price = 81.04,
            StockQuantity = 6,
            DateAdded = DateTime.Parse("2024-03-06"),
            LastRestocked = DateTime.Parse("2024-01-16"),
            IsAvailable = false,
            SKU = "f9605b5a-1218-4f31-88cb-76782c03e497",
            WarehouseLocation = "D4",
            Weight = 3.08,
            Dimensions = 114.52,
            Color = "Red",
            Material = "Fabric",
            Warranty = "1 Year",
            Supplier = "Pena, Flynn and Vasquez",
            Description = "Available guess part so.",
            Discount = 16.54,
            CustomerRating = 5,
            TimesPurchased = 256
        },
        new()
        {
            ProductID = 11,
            Name = "Mission",
            Category = "Toys",
            Manufacturer = "Horton PLC",
            Price = 297.81,
            StockQuantity = 88,
            DateAdded = DateTime.Parse("2024-07-15"),
            LastRestocked = DateTime.Parse("2024-07-02"),
            IsAvailable = true,
            SKU = "772369c4-36c8-4e03-b276-50887f1d14da",
            WarehouseLocation = "A1",
            Weight = 44.93,
            Dimensions = 193.39,
            Color = "Green",
            Material = "Fabric",
            Warranty = "3 Years",
            Supplier = "Carlson PLC",
            Description = "Decision return clear child on do adult goal.",
            Discount = 3.07,
            CustomerRating = 1,
            TimesPurchased = 952
        },
        new()
        {
            ProductID = 12,
            Name = "Listen",
            Category = "Clothing",
            Manufacturer = "Johnson-Snyder",
            Price = 225.01,
            StockQuantity = 18,
            DateAdded = DateTime.Parse("2020-12-18"),
            LastRestocked = DateTime.Parse("2024-09-26"),
            IsAvailable = true,
            SKU = "452985eb-d9ea-4290-91c9-babbc33121ac",
            WarehouseLocation = "E5",
            Weight = 24.79,
            Dimensions = 76.0,
            Color = "Red",
            Material = "Metal",
            Warranty = "1 Year",
            Supplier = "Reynolds, Roberts and Greer",
            Description = "Happy system public oil and partner special.",
            Discount = 10.49,
            CustomerRating = 1,
            TimesPurchased = 977
        },
        new()
        {
            ProductID = 13,
            Name = "Produce",
            Category = "Toys",
            Manufacturer = "Gibbs-Cuevas",
            Price = 54.6,
            StockQuantity = 89,
            DateAdded = DateTime.Parse("2023-05-04"),
            LastRestocked = DateTime.Parse("2024-07-18"),
            IsAvailable = true,
            SKU = "fefb757e-d800-461c-95ff-b751fc051bc9",
            WarehouseLocation = "E5",
            Weight = 32.19,
            Dimensions = 172.33,
            Color = "Red",
            Material = "Fabric",
            Warranty = "3 Years",
            Supplier = "Stevens-Jones",
            Description = "Party mouth attack player mission world fill hit.",
            Discount = 19.68,
            CustomerRating = 3,
            TimesPurchased = 614
        },
        new()
        {
            ProductID = 14,
            Name = "Wind",
            Category = "Furniture",
            Manufacturer = "Davis and Sons",
            Price = 143.79,
            StockQuantity = 21,
            DateAdded = DateTime.Parse("2022-08-31"),
            LastRestocked = DateTime.Parse("2024-07-15"),
            IsAvailable = true,
            SKU = "b94a877e-d01c-4a49-999c-ec12e0a47423",
            WarehouseLocation = "A1",
            Weight = 32.99,
            Dimensions = 92.44,
            Color = "Green",
            Material = "Wood",
            Warranty = "2 Years",
            Supplier = "Ochoa LLC",
            Description = "Hotel break physical bit.",
            Discount = 17.22,
            CustomerRating = 3,
            TimesPurchased = 46
        },
        new()
        {
            ProductID = 15,
            Name = "Measure",
            Category = "Furniture",
            Manufacturer = "Stephenson Group",
            Price = 76.92,
            StockQuantity = 69,
            DateAdded = DateTime.Parse("2021-08-30"),
            LastRestocked = DateTime.Parse("2024-06-21"),
            IsAvailable = false,
            SKU = "b30b1a7b-7494-47ca-b2be-7be5bfb911f6",
            WarehouseLocation = "E5",
            Weight = 40.44,
            Dimensions = 14.61,
            Color = "Yellow",
            Material = "Fabric",
            Warranty = "3 Years",
            Supplier = "Patrick-Harris",
            Description = "Investment important media nor.",
            Discount = 29.7,
            CustomerRating = 5,
            TimesPurchased = 556
        },
        new()
        {
            ProductID = 16,
            Name = "Purpose",
            Category = "Toys",
            Manufacturer = "Silva-Johnson",
            Price = 312.12,
            StockQuantity = 31,
            DateAdded = DateTime.Parse("2024-02-29"),
            LastRestocked = DateTime.Parse("2024-07-09"),
            IsAvailable = false,
            SKU = "51ffc70a-18c9-4498-806e-48ce0a8b94db",
            WarehouseLocation = "E5",
            Weight = 13.11,
            Dimensions = 176.27,
            Color = "Yellow",
            Material = "Plastic",
            Warranty = "1 Year",
            Supplier = "Carpenter-Pope",
            Description = "Coach walk road.",
            Discount = 20.44,
            CustomerRating = 2,
            TimesPurchased = 947
        },
        new()
        {
            ProductID = 17,
            Name = "Make",
            Category = "Electronics",
            Manufacturer = "Alexander-Brown",
            Price = 284.46,
            StockQuantity = 15,
            DateAdded = DateTime.Parse("2023-11-02"),
            LastRestocked = DateTime.Parse("2024-02-02"),
            IsAvailable = true,
            SKU = "e6d2ea27-efde-4367-8f80-4250fadc7fd4",
            WarehouseLocation = "B2",
            Weight = 40.07,
            Dimensions = 194.79,
            Color = "Green",
            Material = "Fabric",
            Warranty = "2 Years",
            Supplier = "Hunt, Carter and Wiggins",
            Description = "Outside ok his shoulder every reduce design.",
            Discount = 28.56,
            CustomerRating = 2,
            TimesPurchased = 957
        },
        new()
        {
            ProductID = 18,
            Name = "Subject",
            Category = "Furniture",
            Manufacturer = "Edwards, Rogers and Nicholson",
            Price = 465.28,
            StockQuantity = 3,
            DateAdded = DateTime.Parse("2021-02-27"),
            LastRestocked = DateTime.Parse("2024-04-01"),
            IsAvailable = false,
            SKU = "7d4e95ac-719b-467e-879d-2ff9684a78ba",
            WarehouseLocation = "A1",
            Weight = 37.97,
            Dimensions = 10.74,
            Color = "Green",
            Material = "Glass",
            Warranty = "2 Years",
            Supplier = "Hebert and Sons",
            Description = "Your level picture one.",
            Discount = 21.22,
            CustomerRating = 4,
            TimesPurchased = 933
        },
        new()
        {
            ProductID = 19,
            Name = "Describe",
            Category = "Clothing",
            Manufacturer = "Butler Group",
            Price = 237.66,
            StockQuantity = 41,
            DateAdded = DateTime.Parse("2024-09-04"),
            LastRestocked = DateTime.Parse("2024-06-15"),
            IsAvailable = true,
            SKU = "857f30b1-9303-475a-a6d6-ae272d2da340",
            WarehouseLocation = "E5",
            Weight = 33.51,
            Dimensions = 161.99,
            Color = "Yellow",
            Material = "Fabric",
            Warranty = "1 Year",
            Supplier = "Townsend-Holt",
            Description = "Bring while whose accept season statement.",
            Discount = 10.27,
            CustomerRating = 2,
            TimesPurchased = 726
        },
        new()
        {
            ProductID = 20,
            Name = "These",
            Category = "Electronics",
            Manufacturer = "Mitchell Inc",
            Price = 419.52,
            StockQuantity = 21,
            DateAdded = DateTime.Parse("2022-05-24"),
            LastRestocked = DateTime.Parse("2024-02-14"),
            IsAvailable = false,
            SKU = "30fc3c1e-8571-42c4-adf5-6e90066a8730",
            WarehouseLocation = "A1",
            Weight = 45.56,
            Dimensions = 139.02,
            Color = "Red",
            Material = "Wood",
            Warranty = "1 Year",
            Supplier = "Hernandez and Sons",
            Description = "Father wear every attorney in figure.",
            Discount = 6.45,
            CustomerRating = 2,
            TimesPurchased = 342
        },
        new()
        {
            ProductID = 21,
            Name = "Final",
            Category = "Toys",
            Manufacturer = "Gordon, Mullen and Jackson",
            Price = 190.68,
            StockQuantity = 40,
            DateAdded = DateTime.Parse("2021-07-12"),
            LastRestocked = DateTime.Parse("2024-06-06"),
            IsAvailable = false,
            SKU = "5ea83c56-4987-416b-81e3-1e341c562de2",
            WarehouseLocation = "C3",
            Weight = 23.95,
            Dimensions = 22.16,
            Color = "Black",
            Material = "Fabric",
            Warranty = "2 Years",
            Supplier = "Kelley Ltd",
            Description = "Concern serve become full government special especially.",
            Discount = 1.28,
            CustomerRating = 1,
            TimesPurchased = 352
        },
        new()
        {
            ProductID = 22,
            Name = "Listen",
            Category = "Household",
            Manufacturer = "Carpenter-Jones",
            Price = 418.05,
            StockQuantity = 100,
            DateAdded = DateTime.Parse("2020-07-26"),
            LastRestocked = DateTime.Parse("2024-01-25"),
            IsAvailable = false,
            SKU = "d66b567e-9166-46c7-a0c8-2cf08656681f",
            WarehouseLocation = "A1",
            Weight = 23.09,
            Dimensions = 27.33,
            Color = "Red",
            Material = "Plastic",
            Warranty = "3 Years",
            Supplier = "Stevens, Daniels and Miller",
            Description = "Apply those also show can attack decide sing.",
            Discount = 0.65,
            CustomerRating = 5,
            TimesPurchased = 355
        },
        new()
        {
            ProductID = 23,
            Name = "Score",
            Category = "Clothing",
            Manufacturer = "Greer-Soto",
            Price = 431.31,
            StockQuantity = 43,
            DateAdded = DateTime.Parse("2021-08-16"),
            LastRestocked = DateTime.Parse("2024-10-23"),
            IsAvailable = false,
            SKU = "39c13021-ac74-4c2e-96cb-d3bf7ae0bd29",
            WarehouseLocation = "B2",
            Weight = 14.02,
            Dimensions = 7.7,
            Color = "Green",
            Material = "Wood",
            Warranty = "1 Year",
            Supplier = "Alvarado, Williams and Hamilton",
            Description = "American that myself half as city significant whatever.",
            Discount = 19.44,
            CustomerRating = 3,
            TimesPurchased = 425
        },
        new()
        {
            ProductID = 24,
            Name = "Experience",
            Category = "Household",
            Manufacturer = "Lewis PLC",
            Price = 130.06,
            StockQuantity = 97,
            DateAdded = DateTime.Parse("2022-11-11"),
            LastRestocked = DateTime.Parse("2024-05-11"),
            IsAvailable = false,
            SKU = "b43936a6-52c2-4da4-902a-89e747a9bbb3",
            WarehouseLocation = "A1",
            Weight = 8.66,
            Dimensions = 90.87,
            Color = "Black",
            Material = "Plastic",
            Warranty = "2 Years",
            Supplier = "Martinez-Miller",
            Description = "Art start federal record there quality.",
            Discount = 9.21,
            CustomerRating = 4,
            TimesPurchased = 927
        },
        new()
        {
            ProductID = 25,
            Name = "Summer",
            Category = "Household",
            Manufacturer = "Oconnor Group",
            Price = 418.0,
            StockQuantity = 74,
            DateAdded = DateTime.Parse("2022-12-10"),
            LastRestocked = DateTime.Parse("2024-07-30"),
            IsAvailable = true,
            SKU = "c130ceba-8631-41df-8c33-5b97ce49846b",
            WarehouseLocation = "E5",
            Weight = 17.01,
            Dimensions = 68.52,
            Color = "Black",
            Material = "Fabric",
            Warranty = "3 Years",
            Supplier = "Vazquez Ltd",
            Description = "Interest magazine rest goal dark player.",
            Discount = 10.52,
            CustomerRating = 4,
            TimesPurchased = 939
        },
        new()
        {
            ProductID = 26,
            Name = "Lay",
            Category = "Electronics",
            Manufacturer = "Marks Inc",
            Price = 351.86,
            StockQuantity = 94,
            DateAdded = DateTime.Parse("2020-06-14"),
            LastRestocked = DateTime.Parse("2024-04-28"),
            IsAvailable = false,
            SKU = "033831e3-870d-47f3-a1ac-1922d9f794c3",
            WarehouseLocation = "A1",
            Weight = 21.63,
            Dimensions = 189.36,
            Color = "Green",
            Material = "Plastic",
            Warranty = "3 Years",
            Supplier = "Cross, Rodgers and Robinson",
            Description = "Few morning occur ago stay idea image.",
            Discount = 20.32,
            CustomerRating = 5,
            TimesPurchased = 631
        },
        new()
        {
            ProductID = 27,
            Name = "Product",
            Category = "Tools",
            Manufacturer = "Hansen-Sanders",
            Price = 299.6,
            StockQuantity = 50,
            DateAdded = DateTime.Parse("2023-01-02"),
            LastRestocked = DateTime.Parse("2024-03-15"),
            IsAvailable = false,
            SKU = "02c77dc7-11d7-4be4-a8f7-7bc645f3b23a",
            WarehouseLocation = "C3",
            Weight = 16.28,
            Dimensions = 25.94,
            Color = "White",
            Material = "Wood",
            Warranty = "3 Years",
            Supplier = "Morales, Gonzalez and Roberts",
            Description = "Seem he most certain.",
            Discount = 10.82,
            CustomerRating = 1,
            TimesPurchased = 457
        },
        new()
        {
            ProductID = 28,
            Name = "Machine",
            Category = "Furniture",
            Manufacturer = "Francis-Bishop",
            Price = 468.79,
            StockQuantity = 38,
            DateAdded = DateTime.Parse("2020-07-05"),
            LastRestocked = DateTime.Parse("2024-10-26"),
            IsAvailable = true,
            SKU = "a55fcddb-a54a-4d1d-858c-b32d4886743b",
            WarehouseLocation = "E5",
            Weight = 37.46,
            Dimensions = 56.7,
            Color = "Red",
            Material = "Fabric",
            Warranty = "3 Years",
            Supplier = "Castro LLC",
            Description = "Note too soldier send himself Republican loss.",
            Discount = 6.44,
            CustomerRating = 4,
            TimesPurchased = 540
        },
        new()
        {
            ProductID = 29,
            Name = "Energy",
            Category = "Furniture",
            Manufacturer = "Guzman, Johnson and Hickman",
            Price = 294.37,
            StockQuantity = 29,
            DateAdded = DateTime.Parse("2020-12-09"),
            LastRestocked = DateTime.Parse("2024-04-09"),
            IsAvailable = false,
            SKU = "0667c6a6-e1f3-4616-8d42-a4e2fc8380ba",
            WarehouseLocation = "B2",
            Weight = 20.03,
            Dimensions = 81.16,
            Color = "Red",
            Material = "Metal",
            Warranty = "2 Years",
            Supplier = "Lewis, Turner and Thomas",
            Description = "Born baby run wide news their.",
            Discount = 22.66,
            CustomerRating = 2,
            TimesPurchased = 683
        },
        new()
        {
            ProductID = 30,
            Name = "Evidence",
            Category = "Clothing",
            Manufacturer = "Reeves-Melton",
            Price = 487.19,
            StockQuantity = 63,
            DateAdded = DateTime.Parse("2020-10-04"),
            LastRestocked = DateTime.Parse("2024-08-02"),
            IsAvailable = false,
            SKU = "f38e8431-9db4-446e-8795-e152211c7375",
            WarehouseLocation = "C3",
            Weight = 11.96,
            Dimensions = 121.62,
            Color = "Red",
            Material = "Metal",
            Warranty = "1 Year",
            Supplier = "Thompson-Hughes",
            Description = "Quality identify at.",
            Discount = 5.11,
            CustomerRating = 2,
            TimesPurchased = 902
        },
        new()
        {
            ProductID = 31,
            Name = "Player",
            Category = "Electronics",
            Manufacturer = "Powell and Sons",
            Price = 57.82,
            StockQuantity = 45,
            DateAdded = DateTime.Parse("2021-07-29"),
            LastRestocked = DateTime.Parse("2024-10-01"),
            IsAvailable = false,
            SKU = "63024563-d66e-460f-a035-99b45116fac0",
            WarehouseLocation = "A1",
            Weight = 36.8,
            Dimensions = 192.62,
            Color = "White",
            Material = "Glass",
            Warranty = "No Warranty",
            Supplier = "Watson-Harrison",
            Description = "Fight news traditional develop tell.",
            Discount = 23.84,
            CustomerRating = 4,
            TimesPurchased = 22
        },
        new()
        {
            ProductID = 32,
            Name = "Involve",
            Category = "Toys",
            Manufacturer = "Navarro, Armstrong and Miles",
            Price = 279.09,
            StockQuantity = 84,
            DateAdded = DateTime.Parse("2020-06-11"),
            LastRestocked = DateTime.Parse("2024-03-25"),
            IsAvailable = true,
            SKU = "78ae4265-64f2-4335-b957-380b42554a99",
            WarehouseLocation = "E5",
            Weight = 39.91,
            Dimensions = 167.05,
            Color = "Blue",
            Material = "Plastic",
            Warranty = "1 Year",
            Supplier = "Bryant-Benson",
            Description = "Seem I guess take future use enjoy.",
            Discount = 19.17,
            CustomerRating = 1,
            TimesPurchased = 502
        },
        new()
        {
            ProductID = 33,
            Name = "This",
            Category = "Tools",
            Manufacturer = "Flores-Smith",
            Price = 363.96,
            StockQuantity = 29,
            DateAdded = DateTime.Parse("2020-09-26"),
            LastRestocked = DateTime.Parse("2024-03-23"),
            IsAvailable = false,
            SKU = "24e15ee6-1c53-4f00-bee4-5c29df1f6cf0",
            WarehouseLocation = "E5",
            Weight = 46.46,
            Dimensions = 109.9,
            Color = "White",
            Material = "Wood",
            Warranty = "1 Year",
            Supplier = "Wong Inc",
            Description = "Break marriage while huge.",
            Discount = 25.01,
            CustomerRating = 4,
            TimesPurchased = 866
        },
        new()
        {
            ProductID = 34,
            Name = "Service",
            Category = "Household",
            Manufacturer = "Thornton-Herring",
            Price = 62.65,
            StockQuantity = 49,
            DateAdded = DateTime.Parse("2021-09-12"),
            LastRestocked = DateTime.Parse("2024-06-18"),
            IsAvailable = false,
            SKU = "55c95230-6bae-455f-a403-43e64a442ca7",
            WarehouseLocation = "B2",
            Weight = 32.48,
            Dimensions = 25.34,
            Color = "Red",
            Material = "Plastic",
            Warranty = "No Warranty",
            Supplier = "Adkins-Diaz",
            Description = "Allow center group office.",
            Discount = 22.69,
            CustomerRating = 1,
            TimesPurchased = 973
        },
        new()
        {
            ProductID = 35,
            Name = "Buy",
            Category = "Furniture",
            Manufacturer = "Vargas Ltd",
            Price = 153.23,
            StockQuantity = 70,
            DateAdded = DateTime.Parse("2023-03-27"),
            LastRestocked = DateTime.Parse("2024-08-29"),
            IsAvailable = true,
            SKU = "229bb1b1-4e7a-47b8-8942-18819ef6e9f8",
            WarehouseLocation = "E5",
            Weight = 4.1,
            Dimensions = 168.09,
            Color = "Blue",
            Material = "Wood",
            Warranty = "No Warranty",
            Supplier = "Horton, Anderson and Smith",
            Description = "Design throughout left power try.",
            Discount = 3.77,
            CustomerRating = 4,
            TimesPurchased = 23
        },
        new()
        {
            ProductID = 36,
            Name = "She",
            Category = "Clothing",
            Manufacturer = "Ware, Pennington and Miller",
            Price = 485.57,
            StockQuantity = 65,
            DateAdded = DateTime.Parse("2021-02-06"),
            LastRestocked = DateTime.Parse("2024-04-26"),
            IsAvailable = false,
            SKU = "6f7b63bd-85bc-45a5-9d04-aeff8f6d6299",
            WarehouseLocation = "D4",
            Weight = 10.33,
            Dimensions = 114.23,
            Color = "Red",
            Material = "Wood",
            Warranty = "1 Year",
            Supplier = "Miller Ltd",
            Description = "Almost civil measure at happen day.",
            Discount = 15.37,
            CustomerRating = 5,
            TimesPurchased = 520
        },
        new()
        {
            ProductID = 37,
            Name = "Unit",
            Category = "Toys",
            Manufacturer = "Smith, Sanchez and Smith",
            Price = 67.18,
            StockQuantity = 91,
            DateAdded = DateTime.Parse("2021-06-18"),
            LastRestocked = DateTime.Parse("2024-05-22"),
            IsAvailable = false,
            SKU = "9db72222-dda2-44f7-9f47-53e7b4fa9eca",
            WarehouseLocation = "E5",
            Weight = 49.45,
            Dimensions = 186.48,
            Color = "Green",
            Material = "Wood",
            Warranty = "No Warranty",
            Supplier = "Wang-Wilson",
            Description = "Try scene third relationship.",
            Discount = 20.83,
            CustomerRating = 1,
            TimesPurchased = 314
        },
        new()
        {
            ProductID = 38,
            Name = "Expect",
            Category = "Clothing",
            Manufacturer = "Herrera-Rodriguez",
            Price = 262.78,
            StockQuantity = 99,
            DateAdded = DateTime.Parse("2021-10-02"),
            LastRestocked = DateTime.Parse("2024-02-25"),
            IsAvailable = false,
            SKU = "b6ba2888-1911-474a-9b69-7462bd8ebd45",
            WarehouseLocation = "E5",
            Weight = 33.44,
            Dimensions = 146.02,
            Color = "Black",
            Material = "Fabric",
            Warranty = "1 Year",
            Supplier = "Campbell-Wright",
            Description = "Recent then sport fish any.",
            Discount = 6.69,
            CustomerRating = 3,
            TimesPurchased = 561
        },
        new()
        {
            ProductID = 39,
            Name = "For",
            Category = "Tools",
            Manufacturer = "Green, Martin and Love",
            Price = 95.05,
            StockQuantity = 27,
            DateAdded = DateTime.Parse("2022-10-24"),
            LastRestocked = DateTime.Parse("2024-02-26"),
            IsAvailable = true,
            SKU = "ad6471dd-7c2a-4223-89bd-d4f089e62581",
            WarehouseLocation = "D4",
            Weight = 4.29,
            Dimensions = 192.88,
            Color = "Red",
            Material = "Wood",
            Warranty = "No Warranty",
            Supplier = "Hill-Jackson",
            Description = "Officer project rather individual among level stuff.",
            Discount = 2.91,
            CustomerRating = 5,
            TimesPurchased = 891
        },
        new()
        {
            ProductID = 40,
            Name = "Just",
            Category = "Electronics",
            Manufacturer = "Hawkins-Lopez",
            Price = 203.17,
            StockQuantity = 16,
            DateAdded = DateTime.Parse("2021-05-08"),
            LastRestocked = DateTime.Parse("2024-09-01"),
            IsAvailable = false,
            SKU = "f754fa34-f27b-462e-ba18-8a79f3063dc9",
            WarehouseLocation = "D4",
            Weight = 26.87,
            Dimensions = 22.44,
            Color = "Yellow",
            Material = "Glass",
            Warranty = "2 Years",
            Supplier = "Jones LLC",
            Description = "Across recent range hour.",
            Discount = 8.3,
            CustomerRating = 1,
            TimesPurchased = 623
        },
        new()
        {
            ProductID = 41,
            Name = "Raise",
            Category = "Tools",
            Manufacturer = "Franklin-Myers",
            Price = 70.44,
            StockQuantity = 1,
            DateAdded = DateTime.Parse("2024-05-17"),
            LastRestocked = DateTime.Parse("2024-11-12"),
            IsAvailable = true,
            SKU = "dfe2e2d1-3ea3-4dd7-b5e9-d84634cc4a19",
            WarehouseLocation = "D4",
            Weight = 17.68,
            Dimensions = 187.51,
            Color = "Yellow",
            Material = "Metal",
            Warranty = "3 Years",
            Supplier = "Thomas-Moore",
            Description = "Myself economy everybody tend.",
            Discount = 17.8,
            CustomerRating = 2,
            TimesPurchased = 228
        },
        new()
        {
            ProductID = 42,
            Name = "World",
            Category = "Tools",
            Manufacturer = "Cook, Mcpherson and Moss",
            Price = 63.52,
            StockQuantity = 76,
            DateAdded = DateTime.Parse("2023-02-09"),
            LastRestocked = DateTime.Parse("2024-01-25"),
            IsAvailable = true,
            SKU = "f20d354e-439d-4309-89ff-405d62090350",
            WarehouseLocation = "C3",
            Weight = 36.62,
            Dimensions = 74.8,
            Color = "Blue",
            Material = "Fabric",
            Warranty = "1 Year",
            Supplier = "Williams LLC",
            Description = "Letter realize along her its.",
            Discount = 20.73,
            CustomerRating = 4,
            TimesPurchased = 68
        },
        new()
        {
            ProductID = 43,
            Name = "Identify",
            Category = "Tools",
            Manufacturer = "Garza Group",
            Price = 417.33,
            StockQuantity = 52,
            DateAdded = DateTime.Parse("2020-02-25"),
            LastRestocked = DateTime.Parse("2024-07-27"),
            IsAvailable = false,
            SKU = "53030ecd-098a-4225-b8d5-80d03012783a",
            WarehouseLocation = "E5",
            Weight = 26.84,
            Dimensions = 149.84,
            Color = "Yellow",
            Material = "Wood",
            Warranty = "No Warranty",
            Supplier = "Hines, Richardson and Lang",
            Description = "Maintain civil hair at.",
            Discount = 17.65,
            CustomerRating = 5,
            TimesPurchased = 245
        },
        new()
        {
            ProductID = 44,
            Name = "Sense",
            Category = "Clothing",
            Manufacturer = "Munoz-Newman",
            Price = 318.08,
            StockQuantity = 100,
            DateAdded = DateTime.Parse("2021-01-27"),
            LastRestocked = DateTime.Parse("2024-06-28"),
            IsAvailable = false,
            SKU = "130a9008-6a71-401b-b2ee-6fbd335d77d3",
            WarehouseLocation = "C3",
            Weight = 48.52,
            Dimensions = 6.22,
            Color = "Green",
            Material = "Fabric",
            Warranty = "1 Year",
            Supplier = "Clark-Russell",
            Description = "Student own serious entire position.",
            Discount = 17.14,
            CustomerRating = 1,
            TimesPurchased = 274
        },
        new()
        {
            ProductID = 45,
            Name = "Attention",
            Category = "Toys",
            Manufacturer = "Hicks-Walls",
            Price = 52.64,
            StockQuantity = 84,
            DateAdded = DateTime.Parse("2024-05-13"),
            LastRestocked = DateTime.Parse("2024-06-21"),
            IsAvailable = true,
            SKU = "07439b4e-404c-4c0e-a541-a98efafbf9c0",
            WarehouseLocation = "C3",
            Weight = 8.25,
            Dimensions = 192.74,
            Color = "White",
            Material = "Fabric",
            Warranty = "No Warranty",
            Supplier = "Powers, Marshall and Jones",
            Description = "Very hard two again.",
            Discount = 12.28,
            CustomerRating = 5,
            TimesPurchased = 126
        },
        new()
        {
            ProductID = 46,
            Name = "Relate",
            Category = "Tools",
            Manufacturer = "Chambers-Frank",
            Price = 126.43,
            StockQuantity = 50,
            DateAdded = DateTime.Parse("2021-06-22"),
            LastRestocked = DateTime.Parse("2024-04-18"),
            IsAvailable = false,
            SKU = "ee926136-e021-4816-af18-311492181777",
            WarehouseLocation = "A1",
            Weight = 18.43,
            Dimensions = 87.63,
            Color = "Blue",
            Material = "Glass",
            Warranty = "No Warranty",
            Supplier = "Parrish, Vazquez and Mcdaniel",
            Description = "Physical any offer piece dinner rest kind.",
            Discount = 23.17,
            CustomerRating = 5,
            TimesPurchased = 244
        },
        new()
        {
            ProductID = 47,
            Name = "Marriage",
            Category = "Electronics",
            Manufacturer = "Bernard and Sons",
            Price = 248.19,
            StockQuantity = 48,
            DateAdded = DateTime.Parse("2020-05-13"),
            LastRestocked = DateTime.Parse("2024-03-01"),
            IsAvailable = false,
            SKU = "2af1cf1e-26d2-4b32-b250-85ea7ecd5cb3",
            WarehouseLocation = "A1",
            Weight = 11.04,
            Dimensions = 42.22,
            Color = "White",
            Material = "Fabric",
            Warranty = "2 Years",
            Supplier = "Livingston LLC",
            Description = "Fill Democrat relationship ever state nothing position.",
            Discount = 24.14,
            CustomerRating = 5,
            TimesPurchased = 757
        },
        new()
        {
            ProductID = 48,
            Name = "Down",
            Category = "Furniture",
            Manufacturer = "Eaton Group",
            Price = 453.05,
            StockQuantity = 67,
            DateAdded = DateTime.Parse("2022-05-02"),
            LastRestocked = DateTime.Parse("2024-08-21"),
            IsAvailable = true,
            SKU = "8dbd2653-4eaf-48ed-a803-a8e99b4163ba",
            WarehouseLocation = "B2",
            Weight = 38.61,
            Dimensions = 178.28,
            Color = "Yellow",
            Material = "Plastic",
            Warranty = "3 Years",
            Supplier = "Hall, Gonzales and Duran",
            Description = "Reduce home those myself.",
            Discount = 13.85,
            CustomerRating = 4,
            TimesPurchased = 649
        },
        new()
        {
            ProductID = 49,
            Name = "Practice",
            Category = "Furniture",
            Manufacturer = "Davis-Stokes",
            Price = 438.35,
            StockQuantity = 43,
            DateAdded = DateTime.Parse("2023-09-13"),
            LastRestocked = DateTime.Parse("2024-05-15"),
            IsAvailable = true,
            SKU = "30b15f58-f402-469d-90a8-9152203dc297",
            WarehouseLocation = "B2",
            Weight = 48.81,
            Dimensions = 168.21,
            Color = "Blue",
            Material = "Fabric",
            Warranty = "2 Years",
            Supplier = "Garcia Inc",
            Description = "Itself arm bank entire eye.",
            Discount = 17.94,
            CustomerRating = 1,
            TimesPurchased = 430
        },
        new()
        {
            ProductID = 50,
            Name = "Me",
            Category = "Tools",
            Manufacturer = "Santos Inc",
            Price = 211.66,
            StockQuantity = 93,
            DateAdded = DateTime.Parse("2021-10-28"),
            LastRestocked = DateTime.Parse("2024-02-06"),
            IsAvailable = true,
            SKU = "81ea2f07-d7e9-4359-931a-a5eabac173a6",
            WarehouseLocation = "A1",
            Weight = 40.57,
            Dimensions = 158.41,
            Color = "White",
            Material = "Metal",
            Warranty = "2 Years",
            Supplier = "Diaz, Hess and Wagner",
            Description = "Stage day these thing challenge continue.",
            Discount = 25.34,
            CustomerRating = 5,
            TimesPurchased = 564
        },
        new()
        {
            ProductID = 51,
            Name = "Line",
            Category = "Electronics",
            Manufacturer = "Quinn-Reyes",
            Price = 405.31,
            StockQuantity = 8,
            DateAdded = DateTime.Parse("2020-09-03"),
            LastRestocked = DateTime.Parse("2024-10-04"),
            IsAvailable = true,
            SKU = "e472bea6-fdb3-4b2d-9f75-84564a9edcd1",
            WarehouseLocation = "C3",
            Weight = 39.17,
            Dimensions = 7.58,
            Color = "Green",
            Material = "Metal",
            Warranty = "No Warranty",
            Supplier = "Leach Group",
            Description = "Meeting computer PM whom dog.",
            Discount = 27.67,
            CustomerRating = 1,
            TimesPurchased = 955
        },
        new()
        {
            ProductID = 52,
            Name = "Or",
            Category = "Furniture",
            Manufacturer = "Allen-Cole",
            Price = 244.97,
            StockQuantity = 96,
            DateAdded = DateTime.Parse("2021-04-08"),
            LastRestocked = DateTime.Parse("2024-01-09"),
            IsAvailable = false,
            SKU = "31e9f357-8cba-4c8e-81da-c23ffea30685",
            WarehouseLocation = "C3",
            Weight = 1.0,
            Dimensions = 58.53,
            Color = "Green",
            Material = "Fabric",
            Warranty = "No Warranty",
            Supplier = "Parker, Reese and Carey",
            Description = "Subject early worry.",
            Discount = 22.91,
            CustomerRating = 1,
            TimesPurchased = 672
        },
        new()
        {
            ProductID = 53,
            Name = "Daughter",
            Category = "Electronics",
            Manufacturer = "Horn, Stout and Shields",
            Price = 283.55,
            StockQuantity = 31,
            DateAdded = DateTime.Parse("2021-02-03"),
            LastRestocked = DateTime.Parse("2024-01-30"),
            IsAvailable = false,
            SKU = "42931f75-5f8d-483d-817f-2390bb15711f",
            WarehouseLocation = "B2",
            Weight = 31.52,
            Dimensions = 94.64,
            Color = "Red",
            Material = "Fabric",
            Warranty = "2 Years",
            Supplier = "Peck, Thomas and Mcclain",
            Description = "Course almost job appear they could he center.",
            Discount = 21.07,
            CustomerRating = 4,
            TimesPurchased = 48
        },
        new()
        {
            ProductID = 54,
            Name = "Movie",
            Category = "Household",
            Manufacturer = "Flores Inc",
            Price = 220.98,
            StockQuantity = 36,
            DateAdded = DateTime.Parse("2021-08-01"),
            LastRestocked = DateTime.Parse("2024-02-12"),
            IsAvailable = false,
            SKU = "1384a336-8fbf-430b-80f0-f4eaee3e08fb",
            WarehouseLocation = "E5",
            Weight = 38.22,
            Dimensions = 22.78,
            Color = "White",
            Material = "Glass",
            Warranty = "No Warranty",
            Supplier = "Parker LLC",
            Description = "Account might together political somebody wind institution.",
            Discount = 0.23,
            CustomerRating = 3,
            TimesPurchased = 685
        },
        new()
        {
            ProductID = 55,
            Name = "Card",
            Category = "Clothing",
            Manufacturer = "Brown Inc",
            Price = 473.16,
            StockQuantity = 75,
            DateAdded = DateTime.Parse("2020-09-28"),
            LastRestocked = DateTime.Parse("2024-08-20"),
            IsAvailable = true,
            SKU = "42f20f2e-c21e-43bb-ac55-9620e8538e82",
            WarehouseLocation = "C3",
            Weight = 47.41,
            Dimensions = 188.52,
            Color = "Blue",
            Material = "Plastic",
            Warranty = "3 Years",
            Supplier = "Simmons-Douglas",
            Description = "Far seat apply suddenly require.",
            Discount = 17.81,
            CustomerRating = 2,
            TimesPurchased = 141
        },
        new()
        {
            ProductID = 56,
            Name = "Series",
            Category = "Clothing",
            Manufacturer = "Barker and Sons",
            Price = 260.93,
            StockQuantity = 96,
            DateAdded = DateTime.Parse("2020-11-08"),
            LastRestocked = DateTime.Parse("2024-06-30"),
            IsAvailable = true,
            SKU = "412faca5-4419-4244-afb3-71e2ec3cbb77",
            WarehouseLocation = "A1",
            Weight = 15.52,
            Dimensions = 45.12,
            Color = "Red",
            Material = "Fabric",
            Warranty = "2 Years",
            Supplier = "Hammond-Mullins",
            Description = "Health why Mr rest dark trial food.",
            Discount = 20.8,
            CustomerRating = 5,
            TimesPurchased = 454
        },
        new()
        {
            ProductID = 57,
            Name = "Today",
            Category = "Tools",
            Manufacturer = "Nunez-Hughes",
            Price = 307.39,
            StockQuantity = 81,
            DateAdded = DateTime.Parse("2024-09-09"),
            LastRestocked = DateTime.Parse("2024-03-15"),
            IsAvailable = false,
            SKU = "9f0da260-e29e-47d7-9af6-0e46275cd054",
            WarehouseLocation = "E5",
            Weight = 8.16,
            Dimensions = 85.69,
            Color = "Yellow",
            Material = "Fabric",
            Warranty = "No Warranty",
            Supplier = "King-Gilbert",
            Description = "Movie upon player finally.",
            Discount = 29.42,
            CustomerRating = 3,
            TimesPurchased = 324
        },
        new()
        {
            ProductID = 58,
            Name = "Minute",
            Category = "Furniture",
            Manufacturer = "Edwards PLC",
            Price = 354.96,
            StockQuantity = 95,
            DateAdded = DateTime.Parse("2022-03-05"),
            LastRestocked = DateTime.Parse("2024-09-22"),
            IsAvailable = true,
            SKU = "281ebce8-f107-4bbc-a714-93e6cf44ad27",
            WarehouseLocation = "E5",
            Weight = 23.14,
            Dimensions = 136.54,
            Color = "Red",
            Material = "Plastic",
            Warranty = "2 Years",
            Supplier = "Wang, Mendez and Smith",
            Description = "Finally blue place.",
            Discount = 27.12,
            CustomerRating = 3,
            TimesPurchased = 247
        },
        new()
        {
            ProductID = 59,
            Name = "Can",
            Category = "Clothing",
            Manufacturer = "Gonzales-Zavala",
            Price = 234.68,
            StockQuantity = 17,
            DateAdded = DateTime.Parse("2022-04-17"),
            LastRestocked = DateTime.Parse("2024-07-11"),
            IsAvailable = false,
            SKU = "e3b68c28-d23a-42ce-9035-16b929f876ea",
            WarehouseLocation = "A1",
            Weight = 2.56,
            Dimensions = 23.09,
            Color = "Yellow",
            Material = "Fabric",
            Warranty = "2 Years",
            Supplier = "Ellis Inc",
            Description = "Far herself pattern matter.",
            Discount = 14.35,
            CustomerRating = 2,
            TimesPurchased = 846
        },
        new()
        {
            ProductID = 60,
            Name = "Guess",
            Category = "Tools",
            Manufacturer = "Henderson, Shepherd and Burch",
            Price = 297.49,
            StockQuantity = 51,
            DateAdded = DateTime.Parse("2022-09-29"),
            LastRestocked = DateTime.Parse("2024-08-09"),
            IsAvailable = false,
            SKU = "b17a394c-170b-4481-9730-bf16c0788aa3",
            WarehouseLocation = "A1",
            Weight = 25.63,
            Dimensions = 124.6,
            Color = "Yellow",
            Material = "Metal",
            Warranty = "2 Years",
            Supplier = "Johnson, Graham and Orr",
            Description = "Analysis head someone raise show.",
            Discount = 0.46,
            CustomerRating = 1,
            TimesPurchased = 986
        },
        new()
        {
            ProductID = 61,
            Name = "Media",
            Category = "Tools",
            Manufacturer = "Miller-Morgan",
            Price = 491.04,
            StockQuantity = 15,
            DateAdded = DateTime.Parse("2024-07-17"),
            LastRestocked = DateTime.Parse("2024-08-28"),
            IsAvailable = true,
            SKU = "7022c561-59c1-423f-ba82-8154011282fb",
            WarehouseLocation = "C3",
            Weight = 38.35,
            Dimensions = 110.22,
            Color = "White",
            Material = "Fabric",
            Warranty = "1 Year",
            Supplier = "Williams Group",
            Description = "Speak enter husband.",
            Discount = 2.89,
            CustomerRating = 1,
            TimesPurchased = 32
        },
        new()
        {
            ProductID = 62,
            Name = "Race",
            Category = "Electronics",
            Manufacturer = "Fields, Valdez and Gilmore",
            Price = 35.19,
            StockQuantity = 57,
            DateAdded = DateTime.Parse("2021-11-15"),
            LastRestocked = DateTime.Parse("2024-01-24"),
            IsAvailable = true,
            SKU = "b9d61664-8ca0-4e7a-a55b-c39d02e4fcfb",
            WarehouseLocation = "C3",
            Weight = 21.68,
            Dimensions = 61.13,
            Color = "Black",
            Material = "Glass",
            Warranty = "2 Years",
            Supplier = "Wagner, Hicks and Armstrong",
            Description = "Official hundred red southern throughout upon.",
            Discount = 18.34,
            CustomerRating = 5,
            TimesPurchased = 937
        },
        new()
        {
            ProductID = 63,
            Name = "Year",
            Category = "Household",
            Manufacturer = "Bell-Mayo",
            Price = 185.15,
            StockQuantity = 23,
            DateAdded = DateTime.Parse("2022-03-01"),
            LastRestocked = DateTime.Parse("2024-08-02"),
            IsAvailable = true,
            SKU = "ac3c54e3-5717-4c33-8782-22b3f3849c71",
            WarehouseLocation = "E5",
            Weight = 23.6,
            Dimensions = 170.03,
            Color = "White",
            Material = "Metal",
            Warranty = "3 Years",
            Supplier = "Wilson-White",
            Description = "Final final tough decade perhaps form president.",
            Discount = 9.78,
            CustomerRating = 2,
            TimesPurchased = 723
        },
        new()
        {
            ProductID = 64,
            Name = "Personal",
            Category = "Household",
            Manufacturer = "Eaton, Pena and Thomas",
            Price = 320.13,
            StockQuantity = 23,
            DateAdded = DateTime.Parse("2020-11-04"),
            LastRestocked = DateTime.Parse("2024-06-26"),
            IsAvailable = true,
            SKU = "5974591e-929e-4839-b4d0-242d0666e00c",
            WarehouseLocation = "B2",
            Weight = 30.56,
            Dimensions = 7.93,
            Color = "Red",
            Material = "Metal",
            Warranty = "1 Year",
            Supplier = "Estrada, Kelley and Young",
            Description = "Party them already.",
            Discount = 24.76,
            CustomerRating = 1,
            TimesPurchased = 964
        },
        new()
        {
            ProductID = 65,
            Name = "Western",
            Category = "Toys",
            Manufacturer = "Ramos-Cross",
            Price = 463.69,
            StockQuantity = 39,
            DateAdded = DateTime.Parse("2020-07-28"),
            LastRestocked = DateTime.Parse("2024-04-17"),
            IsAvailable = false,
            SKU = "e342c05d-aff8-44b2-b83e-2afc32c02846",
            WarehouseLocation = "C3",
            Weight = 40.53,
            Dimensions = 73.78,
            Color = "Green",
            Material = "Fabric",
            Warranty = "3 Years",
            Supplier = "Donaldson, Herrera and Buchanan",
            Description = "Door major conference interview night.",
            Discount = 5.52,
            CustomerRating = 4,
            TimesPurchased = 79
        },
        new()
        {
            ProductID = 66,
            Name = "Order",
            Category = "Household",
            Manufacturer = "Smith-Brown",
            Price = 496.76,
            StockQuantity = 14,
            DateAdded = DateTime.Parse("2021-10-11"),
            LastRestocked = DateTime.Parse("2024-05-10"),
            IsAvailable = true,
            SKU = "02ed2d0a-38d0-4ce5-8310-8e631f41e110",
            WarehouseLocation = "B2",
            Weight = 2.66,
            Dimensions = 170.85,
            Color = "Yellow",
            Material = "Fabric",
            Warranty = "3 Years",
            Supplier = "Oliver, Nunez and Hernandez",
            Description = "Any however first include cause.",
            Discount = 14.92,
            CustomerRating = 2,
            TimesPurchased = 331
        },
        new()
        {
            ProductID = 67,
            Name = "Explain",
            Category = "Household",
            Manufacturer = "Tanner Inc",
            Price = 354.37,
            StockQuantity = 39,
            DateAdded = DateTime.Parse("2021-02-28"),
            LastRestocked = DateTime.Parse("2024-02-04"),
            IsAvailable = true,
            SKU = "b2efbfaf-c534-428e-b0ff-7ef4d584dfdf",
            WarehouseLocation = "D4",
            Weight = 32.06,
            Dimensions = 101.94,
            Color = "Yellow",
            Material = "Fabric",
            Warranty = "2 Years",
            Supplier = "Vasquez Group",
            Description = "Live day company member two gas.",
            Discount = 29.65,
            CustomerRating = 2,
            TimesPurchased = 672
        },
        new()
        {
            ProductID = 68,
            Name = "Above",
            Category = "Toys",
            Manufacturer = "Khan-Boyd",
            Price = 337.01,
            StockQuantity = 67,
            DateAdded = DateTime.Parse("2023-02-03"),
            LastRestocked = DateTime.Parse("2024-08-01"),
            IsAvailable = false,
            SKU = "365c68b0-ceb8-4150-9f66-4b2ab3623054",
            WarehouseLocation = "A1",
            Weight = 41.49,
            Dimensions = 15.9,
            Color = "Yellow",
            Material = "Plastic",
            Warranty = "3 Years",
            Supplier = "Cooley, Martinez and Taylor",
            Description = "Later describe late trip five ball certainly.",
            Discount = 4.8,
            CustomerRating = 5,
            TimesPurchased = 98
        },
        new()
        {
            ProductID = 69,
            Name = "Focus",
            Category = "Clothing",
            Manufacturer = "Foster-Maxwell",
            Price = 26.04,
            StockQuantity = 56,
            DateAdded = DateTime.Parse("2021-03-10"),
            LastRestocked = DateTime.Parse("2024-06-09"),
            IsAvailable = false,
            SKU = "bf69e17e-871e-4fb6-a4c5-70b4aaa0a91a",
            WarehouseLocation = "B2",
            Weight = 20.47,
            Dimensions = 177.88,
            Color = "Blue",
            Material = "Glass",
            Warranty = "2 Years",
            Supplier = "Walker Inc",
            Description = "Play movement walk money lead up responsibility.",
            Discount = 14.0,
            CustomerRating = 2,
            TimesPurchased = 191
        },
        new()
        {
            ProductID = 70,
            Name = "For",
            Category = "Toys",
            Manufacturer = "Callahan-Mcdonald",
            Price = 234.84,
            StockQuantity = 29,
            DateAdded = DateTime.Parse("2022-09-15"),
            LastRestocked = DateTime.Parse("2024-01-09"),
            IsAvailable = true,
            SKU = "45e5cf32-3afc-4b53-847a-4f58d607e581",
            WarehouseLocation = "C3",
            Weight = 23.96,
            Dimensions = 90.2,
            Color = "Green",
            Material = "Fabric",
            Warranty = "No Warranty",
            Supplier = "Meza Group",
            Description = "One sister once dark call myself.",
            Discount = 15.06,
            CustomerRating = 4,
            TimesPurchased = 681
        },
        new()
        {
            ProductID = 71,
            Name = "Bit",
            Category = "Clothing",
            Manufacturer = "Morales-Banks",
            Price = 117.47,
            StockQuantity = 42,
            DateAdded = DateTime.Parse("2023-11-11"),
            LastRestocked = DateTime.Parse("2024-08-25"),
            IsAvailable = false,
            SKU = "72548a68-1338-46b0-9cc8-214fa767830a",
            WarehouseLocation = "E5",
            Weight = 20.64,
            Dimensions = 91.09,
            Color = "Blue",
            Material = "Glass",
            Warranty = "3 Years",
            Supplier = "Fleming PLC",
            Description = "Be admit recent accept region shake sort.",
            Discount = 20.29,
            CustomerRating = 2,
            TimesPurchased = 504
        },
        new()
        {
            ProductID = 72,
            Name = "Best",
            Category = "Toys",
            Manufacturer = "Boyer, Watson and Gibson",
            Price = 81.07,
            StockQuantity = 6,
            DateAdded = DateTime.Parse("2022-01-17"),
            LastRestocked = DateTime.Parse("2024-11-09"),
            IsAvailable = false,
            SKU = "176e7fbe-0507-4124-989b-c1641f14137a",
            WarehouseLocation = "B2",
            Weight = 48.09,
            Dimensions = 127.42,
            Color = "Green",
            Material = "Fabric",
            Warranty = "3 Years",
            Supplier = "King PLC",
            Description = "Performance agent political term forward security.",
            Discount = 4.81,
            CustomerRating = 2,
            TimesPurchased = 88
        },
        new()
        {
            ProductID = 73,
            Name = "Go",
            Category = "Household",
            Manufacturer = "Jensen-Avila",
            Price = 376.56,
            StockQuantity = 43,
            DateAdded = DateTime.Parse("2024-08-27"),
            LastRestocked = DateTime.Parse("2024-07-26"),
            IsAvailable = false,
            SKU = "2603c889-43d0-4316-8e3d-21383bc2adeb",
            WarehouseLocation = "C3",
            Weight = 11.14,
            Dimensions = 144.55,
            Color = "White",
            Material = "Glass",
            Warranty = "3 Years",
            Supplier = "Moreno, Delacruz and Stone",
            Description = "Apply source back policy class suddenly front option.",
            Discount = 16.54,
            CustomerRating = 2,
            TimesPurchased = 121
        },
        new()
        {
            ProductID = 74,
            Name = "Seat",
            Category = "Clothing",
            Manufacturer = "Ware, Neal and Baker",
            Price = 391.43,
            StockQuantity = 1,
            DateAdded = DateTime.Parse("2021-02-20"),
            LastRestocked = DateTime.Parse("2024-09-26"),
            IsAvailable = true,
            SKU = "5409a0f6-e34f-4bc3-8a46-26bbeb766103",
            WarehouseLocation = "E5",
            Weight = 37.71,
            Dimensions = 32.39,
            Color = "Black",
            Material = "Metal",
            Warranty = "1 Year",
            Supplier = "Cooper Ltd",
            Description = "Itself see campaign way under yourself against reason.",
            Discount = 12.39,
            CustomerRating = 2,
            TimesPurchased = 1
        },
        new()
        {
            ProductID = 75,
            Name = "Book",
            Category = "Toys",
            Manufacturer = "Abbott-Liu",
            Price = 232.94,
            StockQuantity = 76,
            DateAdded = DateTime.Parse("2021-12-04"),
            LastRestocked = DateTime.Parse("2024-03-17"),
            IsAvailable = true,
            SKU = "b3936446-12fd-4237-9d47-522fd5648314",
            WarehouseLocation = "A1",
            Weight = 2.43,
            Dimensions = 33.94,
            Color = "Blue",
            Material = "Plastic",
            Warranty = "2 Years",
            Supplier = "Anderson, Lambert and Rice",
            Description = "Team before with evening law sister.",
            Discount = 26.48,
            CustomerRating = 3,
            TimesPurchased = 347
        },
        new()
        {
            ProductID = 76,
            Name = "Sit",
            Category = "Clothing",
            Manufacturer = "Russo-Shah",
            Price = 493.57,
            StockQuantity = 14,
            DateAdded = DateTime.Parse("2021-10-06"),
            LastRestocked = DateTime.Parse("2024-02-17"),
            IsAvailable = true,
            SKU = "463716f2-e722-4d35-8114-651fae2744c1",
            WarehouseLocation = "A1",
            Weight = 2.38,
            Dimensions = 156.45,
            Color = "White",
            Material = "Glass",
            Warranty = "No Warranty",
            Supplier = "Murphy, Martinez and Austin",
            Description = "Deep find customer trouble.",
            Discount = 11.57,
            CustomerRating = 4,
            TimesPurchased = 734
        },
        new()
        {
            ProductID = 77,
            Name = "Respond",
            Category = "Toys",
            Manufacturer = "Cross, Taylor and Mcclure",
            Price = 151.87,
            StockQuantity = 40,
            DateAdded = DateTime.Parse("2022-12-04"),
            LastRestocked = DateTime.Parse("2024-06-23"),
            IsAvailable = true,
            SKU = "a817637f-6252-4785-8e43-0ae123d636c3",
            WarehouseLocation = "A1",
            Weight = 31.46,
            Dimensions = 118.08,
            Color = "Blue",
            Material = "Metal",
            Warranty = "2 Years",
            Supplier = "Curtis Inc",
            Description = "Information account near beautiful.",
            Discount = 23.21,
            CustomerRating = 1,
            TimesPurchased = 286
        },
        new()
        {
            ProductID = 78,
            Name = "Really",
            Category = "Toys",
            Manufacturer = "Scott, Taylor and Hickman",
            Price = 378.3,
            StockQuantity = 59,
            DateAdded = DateTime.Parse("2021-10-13"),
            LastRestocked = DateTime.Parse("2024-08-21"),
            IsAvailable = true,
            SKU = "db928bda-998c-47ea-9270-19d12345f9f4",
            WarehouseLocation = "A1",
            Weight = 31.67,
            Dimensions = 71.7,
            Color = "Blue",
            Material = "Metal",
            Warranty = "2 Years",
            Supplier = "Smith, Poole and Green",
            Description = "One quite why think fish.",
            Discount = 18.65,
            CustomerRating = 2,
            TimesPurchased = 431
        },
        new()
        {
            ProductID = 79,
            Name = "Today",
            Category = "Furniture",
            Manufacturer = "Walls, Peck and Hogan",
            Price = 247.62,
            StockQuantity = 39,
            DateAdded = DateTime.Parse("2024-03-26"),
            LastRestocked = DateTime.Parse("2024-08-11"),
            IsAvailable = false,
            SKU = "0d353423-1b06-4c76-a825-923adb81642e",
            WarehouseLocation = "C3",
            Weight = 36.43,
            Dimensions = 10.32,
            Color = "Yellow",
            Material = "Wood",
            Warranty = "2 Years",
            Supplier = "Sloan, Anderson and Juarez",
            Description = "Possible maintain provide term.",
            Discount = 13.91,
            CustomerRating = 3,
            TimesPurchased = 754
        },
        new()
        {
            ProductID = 80,
            Name = "Year",
            Category = "Clothing",
            Manufacturer = "Hull, Rollins and Smith",
            Price = 245.01,
            StockQuantity = 19,
            DateAdded = DateTime.Parse("2023-02-22"),
            LastRestocked = DateTime.Parse("2024-04-23"),
            IsAvailable = false,
            SKU = "ef7e89b5-fe18-4582-b157-6b07e8103c70",
            WarehouseLocation = "E5",
            Weight = 12.79,
            Dimensions = 134.84,
            Color = "Black",
            Material = "Fabric",
            Warranty = "1 Year",
            Supplier = "Sexton, Bell and James",
            Description = "All knowledge subject.",
            Discount = 0.84,
            CustomerRating = 4,
            TimesPurchased = 133
        },
        new()
        {
            ProductID = 81,
            Name = "Attention",
            Category = "Household",
            Manufacturer = "Cummings-Gould",
            Price = 16.26,
            StockQuantity = 93,
            DateAdded = DateTime.Parse("2024-10-02"),
            LastRestocked = DateTime.Parse("2024-04-02"),
            IsAvailable = true,
            SKU = "cc11396a-5b97-45dc-ac6f-6537ec028811",
            WarehouseLocation = "C3",
            Weight = 34.48,
            Dimensions = 10.98,
            Color = "Green",
            Material = "Glass",
            Warranty = "2 Years",
            Supplier = "Stokes-Jennings",
            Description = "Still begin new person month possible cost.",
            Discount = 23.17,
            CustomerRating = 3,
            TimesPurchased = 98
        },
        new()
        {
            ProductID = 82,
            Name = "It",
            Category = "Tools",
            Manufacturer = "Cantu and Sons",
            Price = 105.27,
            StockQuantity = 93,
            DateAdded = DateTime.Parse("2023-02-28"),
            LastRestocked = DateTime.Parse("2024-11-02"),
            IsAvailable = false,
            SKU = "0e4c9a27-abe4-4546-82a1-6b5e1e4636fe",
            WarehouseLocation = "C3",
            Weight = 1.75,
            Dimensions = 126.34,
            Color = "Red",
            Material = "Metal",
            Warranty = "2 Years",
            Supplier = "Cook-George",
            Description = "Lot people occur respond country.",
            Discount = 13.51,
            CustomerRating = 1,
            TimesPurchased = 720
        },
        new()
        {
            ProductID = 83,
            Name = "Low",
            Category = "Electronics",
            Manufacturer = "Bernard-Edwards",
            Price = 254.09,
            StockQuantity = 30,
            DateAdded = DateTime.Parse("2021-11-22"),
            LastRestocked = DateTime.Parse("2024-02-16"),
            IsAvailable = false,
            SKU = "af073cc2-19c7-4673-9931-b27b57d0703f",
            WarehouseLocation = "D4",
            Weight = 12.42,
            Dimensions = 165.83,
            Color = "White",
            Material = "Fabric",
            Warranty = "No Warranty",
            Supplier = "Mcfarland and Sons",
            Description = "Bank power nor.",
            Discount = 21.62,
            CustomerRating = 3,
            TimesPurchased = 546
        },
        new()
        {
            ProductID = 84,
            Name = "Cold",
            Category = "Household",
            Manufacturer = "Phillips-Wilson",
            Price = 14.4,
            StockQuantity = 91,
            DateAdded = DateTime.Parse("2022-08-01"),
            LastRestocked = DateTime.Parse("2024-02-10"),
            IsAvailable = true,
            SKU = "9dff7753-4380-4ced-870b-2e87fef748fd",
            WarehouseLocation = "B2",
            Weight = 10.5,
            Dimensions = 143.6,
            Color = "Black",
            Material = "Plastic",
            Warranty = "No Warranty",
            Supplier = "Franklin-Walters",
            Description = "Short side defense idea hospital service at.",
            Discount = 29.58,
            CustomerRating = 3,
            TimesPurchased = 611
        },
        new()
        {
            ProductID = 85,
            Name = "Improve",
            Category = "Tools",
            Manufacturer = "Moon PLC",
            Price = 395.44,
            StockQuantity = 61,
            DateAdded = DateTime.Parse("2020-04-14"),
            LastRestocked = DateTime.Parse("2024-04-17"),
            IsAvailable = false,
            SKU = "552cd5f8-d97e-49dc-99eb-ab92ccf63cbe",
            WarehouseLocation = "D4",
            Weight = 41.62,
            Dimensions = 64.87,
            Color = "Yellow",
            Material = "Wood",
            Warranty = "3 Years",
            Supplier = "Simmons-Warren",
            Description = "Research eye room necessary order.",
            Discount = 16.33,
            CustomerRating = 5,
            TimesPurchased = 366
        },
        new()
        {
            ProductID = 86,
            Name = "Play",
            Category = "Clothing",
            Manufacturer = "Adams, Bradley and Nicholson",
            Price = 69.64,
            StockQuantity = 77,
            DateAdded = DateTime.Parse("2024-03-26"),
            LastRestocked = DateTime.Parse("2024-04-17"),
            IsAvailable = false,
            SKU = "d8f49256-6371-4120-8f0f-d0e829f63e00",
            WarehouseLocation = "C3",
            Weight = 11.54,
            Dimensions = 55.03,
            Color = "Red",
            Material = "Glass",
            Warranty = "1 Year",
            Supplier = "Dean LLC",
            Description = "No rise imagine third performance fish able oil.",
            Discount = 21.48,
            CustomerRating = 3,
            TimesPurchased = 679
        },
        new()
        {
            ProductID = 87,
            Name = "Upon",
            Category = "Clothing",
            Manufacturer = "Morris-Wells",
            Price = 430.33,
            StockQuantity = 92,
            DateAdded = DateTime.Parse("2024-08-22"),
            LastRestocked = DateTime.Parse("2024-01-11"),
            IsAvailable = false,
            SKU = "b2072661-8bba-4594-8c10-0f1609a53dd0",
            WarehouseLocation = "E5",
            Weight = 37.15,
            Dimensions = 123.12,
            Color = "Red",
            Material = "Plastic",
            Warranty = "1 Year",
            Supplier = "Hopkins, Ward and Gallegos",
            Description = "But mean national step yes particularly clearly.",
            Discount = 23.46,
            CustomerRating = 4,
            TimesPurchased = 611
        },
        new()
        {
            ProductID = 88,
            Name = "Health",
            Category = "Household",
            Manufacturer = "Johnson LLC",
            Price = 415.69,
            StockQuantity = 29,
            DateAdded = DateTime.Parse("2024-09-24"),
            LastRestocked = DateTime.Parse("2024-04-19"),
            IsAvailable = false,
            SKU = "9a8e8ee2-6a36-4123-b799-76e77ec74c0c",
            WarehouseLocation = "B2",
            Weight = 10.2,
            Dimensions = 140.59,
            Color = "Green",
            Material = "Plastic",
            Warranty = "No Warranty",
            Supplier = "Harrison Inc",
            Description = "Fast however admit election.",
            Discount = 27.86,
            CustomerRating = 1,
            TimesPurchased = 184
        },
        new()
        {
            ProductID = 89,
            Name = "Agree",
            Category = "Furniture",
            Manufacturer = "Montgomery and Sons",
            Price = 133.0,
            StockQuantity = 38,
            DateAdded = DateTime.Parse("2023-11-28"),
            LastRestocked = DateTime.Parse("2024-03-31"),
            IsAvailable = false,
            SKU = "15fe3e45-87af-4c8e-8a9c-6fbde777be6b",
            WarehouseLocation = "C3",
            Weight = 32.63,
            Dimensions = 192.23,
            Color = "Red",
            Material = "Fabric",
            Warranty = "3 Years",
            Supplier = "Hughes, Reed and Edwards",
            Description = "With key fly husband.",
            Discount = 15.39,
            CustomerRating = 5,
            TimesPurchased = 893
        },
        new()
        {
            ProductID = 90,
            Name = "Rate",
            Category = "Electronics",
            Manufacturer = "Silva-Davies",
            Price = 361.98,
            StockQuantity = 40,
            DateAdded = DateTime.Parse("2021-08-07"),
            LastRestocked = DateTime.Parse("2024-07-19"),
            IsAvailable = false,
            SKU = "ae233a8a-82e7-4ead-bb7c-8c83b3d0fdfc",
            WarehouseLocation = "D4",
            Weight = 25.4,
            Dimensions = 197.57,
            Color = "Red",
            Material = "Plastic",
            Warranty = "No Warranty",
            Supplier = "Moreno, Sanders and Fields",
            Description = "My make choose better help.",
            Discount = 9.99,
            CustomerRating = 3,
            TimesPurchased = 215
        },
        new()
        {
            ProductID = 91,
            Name = "Practice",
            Category = "Furniture",
            Manufacturer = "Williams-Hoffman",
            Price = 295.34,
            StockQuantity = 69,
            DateAdded = DateTime.Parse("2022-11-15"),
            LastRestocked = DateTime.Parse("2024-08-08"),
            IsAvailable = false,
            SKU = "e33baef5-b32f-4cab-b58b-7f1428196377",
            WarehouseLocation = "D4",
            Weight = 22.67,
            Dimensions = 61.21,
            Color = "Black",
            Material = "Fabric",
            Warranty = "No Warranty",
            Supplier = "Jones and Sons",
            Description = "Rather central vote shake hair part authority hit.",
            Discount = 15.63,
            CustomerRating = 4,
            TimesPurchased = 463
        },
        new()
        {
            ProductID = 92,
            Name = "Way",
            Category = "Household",
            Manufacturer = "Williams-Martinez",
            Price = 72.62,
            StockQuantity = 5,
            DateAdded = DateTime.Parse("2020-09-22"),
            LastRestocked = DateTime.Parse("2024-01-14"),
            IsAvailable = true,
            SKU = "f16adb95-4238-4398-ad96-6d1a80310444",
            WarehouseLocation = "C3",
            Weight = 31.71,
            Dimensions = 57.66,
            Color = "Black",
            Material = "Metal",
            Warranty = "2 Years",
            Supplier = "Archer, Jones and Martin",
            Description = "Find wide range main.",
            Discount = 14.44,
            CustomerRating = 1,
            TimesPurchased = 16
        },
        new()
        {
            ProductID = 93,
            Name = "Season",
            Category = "Tools",
            Manufacturer = "Reed Group",
            Price = 496.72,
            StockQuantity = 15,
            DateAdded = DateTime.Parse("2021-12-18"),
            LastRestocked = DateTime.Parse("2024-09-25"),
            IsAvailable = false,
            SKU = "b33435c7-972c-4c15-994c-dc1ccc8935bc",
            WarehouseLocation = "B2",
            Weight = 25.9,
            Dimensions = 126.18,
            Color = "Blue",
            Material = "Metal",
            Warranty = "No Warranty",
            Supplier = "Morris, Franco and Case",
            Description = "Commercial institution yard activity safe offer someone outside.",
            Discount = 17.97,
            CustomerRating = 5,
            TimesPurchased = 590
        },
        new()
        {
            ProductID = 94,
            Name = "Economy",
            Category = "Household",
            Manufacturer = "Cox-Chavez",
            Price = 28.3,
            StockQuantity = 44,
            DateAdded = DateTime.Parse("2020-11-29"),
            LastRestocked = DateTime.Parse("2024-03-14"),
            IsAvailable = true,
            SKU = "25aaee91-26d4-46ca-92d8-1f8fd6c6e51b",
            WarehouseLocation = "D4",
            Weight = 42.59,
            Dimensions = 88.04,
            Color = "Green",
            Material = "Metal",
            Warranty = "No Warranty",
            Supplier = "Walker PLC",
            Description = "This character shake someone then service enough none.",
            Discount = 7.84,
            CustomerRating = 4,
            TimesPurchased = 35
        },
        new()
        {
            ProductID = 95,
            Name = "Study",
            Category = "Electronics",
            Manufacturer = "Quinn, Taylor and Chavez",
            Price = 322.65,
            StockQuantity = 38,
            DateAdded = DateTime.Parse("2020-02-09"),
            LastRestocked = DateTime.Parse("2024-08-23"),
            IsAvailable = false,
            SKU = "3c36f67f-04b6-4819-a6d8-51805e56d05f",
            WarehouseLocation = "B2",
            Weight = 9.43,
            Dimensions = 12.19,
            Color = "White",
            Material = "Wood",
            Warranty = "No Warranty",
            Supplier = "Miller and Sons",
            Description = "Compare gas team staff.",
            Discount = 17.56,
            CustomerRating = 5,
            TimesPurchased = 319
        },
        new()
        {
            ProductID = 96,
            Name = "Response",
            Category = "Furniture",
            Manufacturer = "Miller, Griffin and Russell",
            Price = 401.45,
            StockQuantity = 65,
            DateAdded = DateTime.Parse("2020-02-04"),
            LastRestocked = DateTime.Parse("2024-09-06"),
            IsAvailable = true,
            SKU = "0261a844-d910-45a6-ab8b-d83aa82df3ee",
            WarehouseLocation = "A1",
            Weight = 48.43,
            Dimensions = 113.94,
            Color = "Red",
            Material = "Wood",
            Warranty = "2 Years",
            Supplier = "Manning PLC",
            Description = "Develop against suddenly hard.",
            Discount = 27.38,
            CustomerRating = 3,
            TimesPurchased = 946
        },
        new()
        {
            ProductID = 97,
            Name = "Develop",
            Category = "Household",
            Manufacturer = "Ward, Collins and Guerrero",
            Price = 375.98,
            StockQuantity = 74,
            DateAdded = DateTime.Parse("2023-03-14"),
            LastRestocked = DateTime.Parse("2024-05-12"),
            IsAvailable = true,
            SKU = "a6d33249-0c6a-4c21-9ba6-ebbed6f78866",
            WarehouseLocation = "C3",
            Weight = 14.02,
            Dimensions = 42.77,
            Color = "Blue",
            Material = "Plastic",
            Warranty = "No Warranty",
            Supplier = "Smith, Peterson and Craig",
            Description = "If difficult bank work respond option.",
            Discount = 23.06,
            CustomerRating = 3,
            TimesPurchased = 962
        },
        new()
        {
            ProductID = 98,
            Name = "Also",
            Category = "Toys",
            Manufacturer = "Johnson-Hughes",
            Price = 386.42,
            StockQuantity = 27,
            DateAdded = DateTime.Parse("2020-08-05"),
            LastRestocked = DateTime.Parse("2024-02-06"),
            IsAvailable = true,
            SKU = "19199dac-b7cc-4235-b924-5470460e64c2",
            WarehouseLocation = "C3",
            Weight = 44.17,
            Dimensions = 25.09,
            Color = "Green",
            Material = "Fabric",
            Warranty = "2 Years",
            Supplier = "Boyd-Munoz",
            Description = "Subject rich exactly star deep attack.",
            Discount = 4.79,
            CustomerRating = 1,
            TimesPurchased = 791
        },
        new()
        {
            ProductID = 99,
            Name = "Majority",
            Category = "Tools",
            Manufacturer = "Garrett Inc",
            Price = 24.65,
            StockQuantity = 61,
            DateAdded = DateTime.Parse("2024-10-01"),
            LastRestocked = DateTime.Parse("2024-03-11"),
            IsAvailable = false,
            SKU = "f13bde31-297f-4ca5-9fcf-56a5e97653e1",
            WarehouseLocation = "A1",
            Weight = 26.63,
            Dimensions = 194.91,
            Color = "Green",
            Material = "Fabric",
            Warranty = "No Warranty",
            Supplier = "Cox PLC",
            Description = "Expert should member history tough maintain.",
            Discount = 9.63,
            CustomerRating = 1,
            TimesPurchased = 197
        },
        new()
        {
            ProductID = 100,
            Name = "Individual",
            Category = "Clothing",
            Manufacturer = "Spencer, Rodriguez and Martinez",
            Price = 158.47,
            StockQuantity = 45,
            DateAdded = DateTime.Parse("2022-05-10"),
            LastRestocked = DateTime.Parse("2024-01-02"),
            IsAvailable = true,
            SKU = "3d7799ae-ed01-4ee8-955a-17c84360f3c7",
            WarehouseLocation = "B2",
            Weight = 10.27,
            Dimensions = 127.82,
            Color = "Blue",
            Material = "Glass",
            Warranty = "3 Years",
            Supplier = "Boyer Inc",
            Description = "Yourself turn season organization weight within protect.",
            Discount = 16.58,
            CustomerRating = 5,
            TimesPurchased = 418
        }
    ];

    public DataGridCollectionView GroupedProducts { get; set; }

    //==================================================
    // Constructor.
    //==================================================

    public DataGridViewModel()
    {
        GroupedProducts = new DataGridCollectionView(Products);
        GroupedProducts.GroupDescriptions.Add(new DataGridPathGroupDescription(nameof(ProductViewModel.Category)));
    }
}